// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB14NjeMukS6RNHRMdb6v8rIXR7_DuhStk',
    appId: '1:582003650818:web:3aeac8b0a9c86e5cd7121b',
    messagingSenderId: '582003650818',
    projectId: 'firelogin-f3267',
    authDomain: 'firelogin-f3267.firebaseapp.com',
    storageBucket: 'firelogin-f3267.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvKQehocz69WB1whZWHJeVmvnkq2I2T_w',
    appId: '1:582003650818:android:f91f51e1ee7ab232d7121b',
    messagingSenderId: '582003650818',
    projectId: 'firelogin-f3267',
    storageBucket: 'firelogin-f3267.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbsZGqzU3nuZHvpo4HUZgOwvLl4IIr8kI',
    appId: '1:582003650818:ios:2223e731c6e95282d7121b',
    messagingSenderId: '582003650818',
    projectId: 'firelogin-f3267',
    storageBucket: 'firelogin-f3267.firebasestorage.app',
    iosBundleId: 'com.example.firelogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbsZGqzU3nuZHvpo4HUZgOwvLl4IIr8kI',
    appId: '1:582003650818:ios:2223e731c6e95282d7121b',
    messagingSenderId: '582003650818',
    projectId: 'firelogin-f3267',
    storageBucket: 'firelogin-f3267.firebasestorage.app',
    iosBundleId: 'com.example.firelogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB14NjeMukS6RNHRMdb6v8rIXR7_DuhStk',
    appId: '1:582003650818:web:73751cba65ec69bcd7121b',
    messagingSenderId: '582003650818',
    projectId: 'firelogin-f3267',
    authDomain: 'firelogin-f3267.firebaseapp.com',
    storageBucket: 'firelogin-f3267.firebasestorage.app',
  );
}
